server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: Management
          uri: http://localhost:8082
          predicates:
            - Path=/managements/** 
        - id: Driver
          uri: http://localhost:8083
          predicates:
            - Path=/drivers/** 
        - id: orderStatus
          uri: http://localhost:8084
          predicates:
            - Path= /orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: admin02-order
          uri: http://admin02-order:8080
          predicates:
            - Path=/orders/** 
        - id: admin02-management
          uri: http://admin02-management:8080
          predicates:
            - Path=/managements/** 
        - id: admin02-driver
          uri: http://admin02-driver:8080
          predicates:
            - Path=/drivers/** 
        - id: admin02-orderstatus
          uri: http://admin02-orderstatus:8080
          predicates:
            - Path= /orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
