server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: Management
          uri: http://localhost:8082
          predicates:
            - Path=/managements/** 
        - id: Driver
          uri: http://localhost:8083
          predicates:
            - Path=/drivers/** 
        - id: orderStatus
          uri: http://localhost:8084
          predicates:
            - Path= /orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: a-order
          uri: http://a-order:8080
          predicates:
            - Path=/orders/** 
        - id: a-management
          uri: http://a-management:8080
          predicates:
            - Path=/managements/** 
        - id: a-driver
          uri: http://a-driver:8080
          predicates:
            - Path=/drivers/** 
        - id: a-orderstatus
          uri: http://a-orderstatus:8080
          predicates:
            - Path= /orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
